// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/novel-ui/Login.tsx": () => import("../components/mockups/novel-ui/Login.tsx"),
  "./components/mockups/novel-ui/NovelDetail.tsx": () => import("../components/mockups/novel-ui/NovelDetail.tsx"),
  "./components/mockups/novel-ui/NovelWorkspace.tsx": () => import("../components/mockups/novel-ui/NovelWorkspace.tsx"),
  "./components/mockups/novel-ui/Pricing.tsx": () => import("../components/mockups/novel-ui/Pricing.tsx"),
  "./components/mockups/novel-ui/Register.tsx": () => import("../components/mockups/novel-ui/Register.tsx"),
  "./components/mockups/novel-ui/Settings.tsx": () => import("../components/mockups/novel-ui/Settings.tsx"),
  "./components/mockups/novel-ui/WorkspaceArcMap.tsx": () => import("../components/mockups/novel-ui/WorkspaceArcMap.tsx"),
  "./components/mockups/novel-ui/WorkspaceEntry.tsx": () => import("../components/mockups/novel-ui/WorkspaceEntry.tsx"),
  "./components/mockups/novel-ui/WorkspaceGlass.tsx": () => import("../components/mockups/novel-ui/WorkspaceGlass.tsx"),
  "./components/mockups/novel-ui/WorkspaceInkPaper.tsx": () => import("../components/mockups/novel-ui/WorkspaceInkPaper.tsx"),
  "./components/mockups/novel-ui/WorkspaceMomentum.tsx": () => import("../components/mockups/novel-ui/WorkspaceMomentum.tsx"),
  "./components/mockups/novel-ui/WorkspaceShelf.tsx": () => import("../components/mockups/novel-ui/WorkspaceShelf.tsx"),
  "./components/mockups/novel-ui/WorkspaceTerminal.tsx": () => import("../components/mockups/novel-ui/WorkspaceTerminal.tsx"),
  "./components/mockups/novel-ui/WritingDesk.tsx": () => import("../components/mockups/novel-ui/WritingDesk.tsx")
};
