"""baseline schema

Revision ID: 3d0894d473c4
Revises: 
Create Date: 2026-06-01 21:06:01.324316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d0894d473c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_type', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date', 'model', 'api_type', name='uq_api_usage_log')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_log_date'), ['log_date'], unique=False)

    op.create_table('chapter_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_versions_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('real_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('rag_ingest_hash', sa.String(length=64), nullable=True),
    sa.Column('selected_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_version_id'], ['chapter_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_project_chapter', ['project_id', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_project_id'), ['project_id'], unique=False)

    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=True),
    sa.Column('pay_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_orders_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_orders_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('daily_chapter_limit', sa.Integer(), nullable=False),
    sa.Column('max_novels', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_name'), ['name'], unique=True)

    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_metrics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('writing_archives',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('imperial_edict_id', sa.String(length=50), nullable=False, comment='奏折唯一标识，如 ed_20240315_001'),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(length=200), nullable=True, comment='章节标题'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='edictstatus'), nullable=False, comment='奏折状态'),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True, comment='圣旨下发时间'),
    sa.Column('user_command', sa.Text(), nullable=True, comment='用户写作指令/圣旨内容'),
    sa.Column('additional_requirements', sa.Text(), nullable=True, comment='附加要求/御批'),
    sa.Column('templates_used', sa.JSON(), nullable=True, comment='使用的模板列表'),
    sa.Column('skills_enabled', sa.JSON(), nullable=True, comment='启用的技能列表'),
    sa.Column('workflow', sa.JSON(), nullable=True, comment='Agent 工作流记录 [\n            {\n                "stage": "太子分拣",\n                "agent": "taizi",\n                "status": "completed",\n                "timestamp": "2024-03-15T14:30:22Z",\n                "duration_ms": 1200,\n                "input": {...},\n                "output": {...}\n            }\n        ]'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='任务耗时（毫秒）'),
    sa.Column('final_output', sa.JSON(), nullable=True, comment='最终输出 {\n            "selected_version": 1,\n            "word_count": 4523,\n            "estimated_reading_time": "15分钟"\n        }'),
    sa.Column('quality_metrics', sa.JSON(), nullable=True, comment='质量指标 {\n            "gatekeeper_score": 82,\n            "user_rating": null,\n            "review_details": {...}\n        }'),
    sa.Column('versions_generated', sa.Integer(), nullable=True, comment='生成的版本数量'),
    sa.Column('versions_data', sa.JSON(), nullable=True, comment='版本详细数据'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('preset', sa.String(length=50), nullable=True, comment='使用的预设配置'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（如有）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='档案创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_archives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_archives_imperial_edict_id'), ['imperial_edict_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_writing_archives_project_id'), ['project_id'], unique=False)

    op.create_table('writing_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_templates_name'), ['name'], unique=False)

    op.create_table('blueprint_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_evaluations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_evaluations_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('chapter_reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True, comment='{\n            "consistency": 85,      # 剧情一致性\n            "character_depth": 70,  # 角色立体度\n            "pacing": 90,          # 节奏张力\n            "foreshadowing": 60,   # 伏笔呼应\n            "prose_quality": 75,   # 文笔质量\n            "emotion_curve": 80    # 情绪曲线\n        }'),
    sa.Column('issues', sa.JSON(), nullable=True, comment='[\n            {\n                "type": "foreshadowing",\n                "severity": "high",  # low/medium/high\n                "description": "缺少与第3章伏笔的呼应",\n                "suggestion": "建议在本章结尾添加..."\n            }\n        ]'),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('rewrite_required', sa.Boolean(), nullable=False),
    sa.Column('chapter_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_version_id'], ['chapter_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_reviews_project_id'), ['project_id'], unique=False)

    op.create_table('llm_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider_url', sa.Text(), nullable=True),
    sa.Column('llm_provider_api_key', sa.Text(), nullable=True),
    sa.Column('llm_provider_model', sa.Text(), nullable=True),
    sa.Column('llm_provider_api_format', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('novel_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_novel_ids', sa.JSON(), nullable=True),
    sa.Column('fusion_dna', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novel_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novel_projects_user_id'), ['user_id'], unique=False)

    op.create_table('reference_novels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outline_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('style_samples_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('memory_card', sa.JSON(), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_novels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_novels_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_reference_novels_user_id'), ['user_id'], unique=False)

    op.create_table('user_daily_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_date', name='uq_user_daily')
    )
    with op.batch_alter_table('user_daily_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_requests_user_id'), ['user_id'], unique=False)

    op.create_table('user_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_chapter_limit', sa.Integer(), nullable=False, comment='每日章节生成上限'),
    sa.Column('daily_chapter_used', sa.Integer(), nullable=False, comment='今日已生成章节数'),
    sa.Column('total_chapters_generated', sa.Integer(), nullable=False, comment='累计生成章节数'),
    sa.Column('storage_limit', sa.BigInteger(), nullable=False, comment='存储空间限制（默认 1GB）'),
    sa.Column('storage_used', sa.BigInteger(), nullable=False, comment='已使用存储空间'),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False, comment='每月 token 限制（默认 100 万）'),
    sa.Column('monthly_token_used', sa.Integer(), nullable=False, comment='本月已使用 token'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='是否为 Premium 用户'),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True, comment='Premium 到期时间'),
    sa.Column('daily_reset_at', sa.DateTime(), nullable=False, comment='每日配额重置时间'),
    sa.Column('monthly_reset_at', sa.DateTime(), nullable=False, comment='每月配额重置时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_quotas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_quotas_user_id'), ['user_id'], unique=True)

    op.create_table('user_writing_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_preset', sa.String(length=64), nullable=True),
    sa.Column('custom_rules', sa.Text(), nullable=True),
    sa.Column('banned_phrases', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('blueprint_relationships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('character_from', sa.String(length=255), nullable=False),
    sa.Column('character_to', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blueprint_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blueprint_relationships_project_id'), ['project_id'], unique=False)

    op.create_table('chapter_blueprints',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('suspense_density', sa.String(length=32), nullable=True),
    sa.Column('foreshadowing_ops', sa.String(length=128), nullable=True),
    sa.Column('cognitive_twist_level', sa.Integer(), nullable=False),
    sa.Column('chapter_function', sa.String(length=32), nullable=True),
    sa.Column('chapter_focus', sa.String(length=255), nullable=True),
    sa.Column('suspense_type', sa.String(length=128), nullable=True),
    sa.Column('emotional_arc', sa.String(length=255), nullable=True),
    sa.Column('involved_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('mission_constraints', sa.JSON(), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('director_script', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('beat_sheet', sa.JSON(), nullable=True),
    sa.Column('strand_type', sa.String(length=32), nullable=True),
    sa.Column('strand_weight', sa.Float(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_blueprints_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_blueprints_project_id'), ['project_id'], unique=False)

    op.create_table('chapter_outlines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_outlines', schema=None) as batch_op:
        batch_op.create_index('ix_chapter_outlines_project_chapter', ['project_id', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_outlines_project_id'), ['project_id'], unique=False)

    op.create_table('chapter_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('global_summary_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('character_states_snapshot', sa.JSON(), nullable=True),
    sa.Column('plot_arcs_snapshot', sa.JSON(), nullable=True),
    sa.Column('chapter_summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_snapshots_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_snapshots_project_id'), ['project_id'], unique=False)

    op.create_table('entity_registry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False, comment='character/location/organization/item/ability'),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_chapter', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False, comment='blueprint/manual/auto_detected'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_registry_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_registry_project_id'), ['project_id'], unique=False)

    op.create_table('factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faction_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('leader', sa.String(length=255), nullable=True),
    sa.Column('hierarchy', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.String(length=64), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('recent_events', sa.JSON(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('traditions', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_project_id'), ['project_id'], unique=False)

    op.create_table('foreshadowing_analysis',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('total_foreshadowings', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('abandoned_count', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_distance', sa.Float(), nullable=True),
    sa.Column('unresolved_ratio', sa.Float(), nullable=True),
    sa.Column('pattern_analysis', sa.JSON(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('foreshadowings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_chapter_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('target_reveal_chapter', sa.Integer(), nullable=True),
    sa.Column('reveal_method', sa.Text(), nullable=True),
    sa.Column('reveal_impact', sa.Text(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_plots', sa.JSON(), nullable=True),
    sa.Column('related_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('importance', sa.String(length=32), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('author_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadowings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadowings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreshadowings_status'), ['status'], unique=False)

    op.create_table('novel_blueprints',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.Column('tone', sa.String(length=128), nullable=True),
    sa.Column('one_sentence_summary', sa.Text(), nullable=True),
    sa.Column('full_synopsis', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('world_setting', sa.JSON(), nullable=True),
    sa.Column('golden_finger', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('novel_constitutions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('core_theme', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('core_conflict', sa.String(length=255), nullable=True),
    sa.Column('story_direction', sa.String(length=255), nullable=True),
    sa.Column('core_values', sa.Text(), nullable=True),
    sa.Column('pov_type', sa.String(length=64), nullable=True),
    sa.Column('pov_character', sa.String(length=255), nullable=True),
    sa.Column('pov_restrictions', sa.Text(), nullable=True),
    sa.Column('target_age_group', sa.String(length=64), nullable=True),
    sa.Column('reading_level', sa.String(length=64), nullable=True),
    sa.Column('violence_rating', sa.String(length=64), nullable=True),
    sa.Column('romance_rating', sa.String(length=64), nullable=True),
    sa.Column('overall_tone', sa.String(length=128), nullable=True),
    sa.Column('realism_level', sa.String(length=128), nullable=True),
    sa.Column('language_style', sa.String(length=128), nullable=True),
    sa.Column('world_type', sa.String(length=128), nullable=True),
    sa.Column('power_system', sa.Text(), nullable=True),
    sa.Column('world_rules', sa.JSON(), nullable=True),
    sa.Column('forbidden_content', sa.JSON(), nullable=True),
    sa.Column('allowed_character_types', sa.JSON(), nullable=True),
    sa.Column('character_power_limits', sa.Text(), nullable=True),
    sa.Column('allowed_relationship_types', sa.JSON(), nullable=True),
    sa.Column('allowed_plot_types', sa.JSON(), nullable=True),
    sa.Column('twist_frequency', sa.String(length=128), nullable=True),
    sa.Column('foreshadowing_rules', sa.Text(), nullable=True),
    sa.Column('time_span', sa.String(length=128), nullable=True),
    sa.Column('geographical_scope', sa.String(length=128), nullable=True),
    sa.Column('time_flow', sa.String(length=128), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('novel_conversations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novel_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novel_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('power_systems',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment="体系名称，如 '修仙境界'、'魔法师等级'"),
    sa.Column('description', sa.Text(), nullable=True, comment='体系描述与核心规则'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('power_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_systems_project_id'), ['project_id'], unique=False)

    op.create_table('project_memories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('global_summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('book_summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('plot_arcs', sa.JSON(), nullable=True),
    sa.Column('story_timeline_summary', sa.Text(), nullable=True),
    sa.Column('last_updated_chapter', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memories_project_id'), ['project_id'], unique=True)

    op.create_table('story_time_trackers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('time_system', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('current_date', sa.String(length=64), nullable=True),
    sa.Column('current_time', sa.String(length=64), nullable=True),
    sa.Column('default_chapter_duration', sa.String(length=64), nullable=True),
    sa.Column('chapter_time_map', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('story_date', sa.String(length=64), nullable=True),
    sa.Column('time_elapsed', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('caused_by_event_id', sa.BigInteger(), nullable=True),
    sa.Column('leads_to_event_ids', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('is_turning_point', sa.Boolean(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caused_by_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_project_id'), ['project_id'], unique=False)

    op.create_table('volume_summaries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=False),
    sa.Column('chapter_end', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volume_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_summaries_project_id'), ['project_id'], unique=False)

    op.create_table('writer_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=64), nullable=True),
    sa.Column('sentence_rhythm', sa.Text(), nullable=True),
    sa.Column('vocabulary_preferences', sa.JSON(), nullable=True),
    sa.Column('unique_expressions', sa.JSON(), nullable=True),
    sa.Column('formality_level', sa.String(length=64), nullable=True),
    sa.Column('opening_style', sa.Text(), nullable=True),
    sa.Column('transition_style', sa.Text(), nullable=True),
    sa.Column('ending_style', sa.Text(), nullable=True),
    sa.Column('dialogue_style', sa.Text(), nullable=True),
    sa.Column('dialogue_tags', sa.Text(), nullable=True),
    sa.Column('description_style', sa.Text(), nullable=True),
    sa.Column('show_vs_tell_ratio', sa.String(length=64), nullable=True),
    sa.Column('sensory_focus', sa.JSON(), nullable=True),
    sa.Column('physiological_reactions', sa.JSON(), nullable=True),
    sa.Column('benchmark_texts', sa.JSON(), nullable=True),
    sa.Column('catchphrases', sa.JSON(), nullable=True),
    sa.Column('personal_quirks', sa.JSON(), nullable=True),
    sa.Column('imperfection_patterns', sa.JSON(), nullable=True),
    sa.Column('thinking_pauses', sa.JSON(), nullable=True),
    sa.Column('filler_words', sa.JSON(), nullable=True),
    sa.Column('regional_expressions', sa.JSON(), nullable=True),
    sa.Column('avoid_patterns', sa.JSON(), nullable=True),
    sa.Column('variation_rules', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writer_personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writer_personas_project_id'), ['project_id'], unique=False)

    op.create_table('causal_chains',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('cause_type', sa.String(length=64), nullable=True),
    sa.Column('cause_description', sa.Text(), nullable=False),
    sa.Column('cause_chapter', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=64), nullable=True),
    sa.Column('effect_description', sa.Text(), nullable=False),
    sa.Column('effect_chapter', sa.Integer(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('cause_event_id', sa.BigInteger(), nullable=True),
    sa.Column('effect_event_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resolution_description', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['effect_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('causal_chains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_causal_chains_project_id'), ['project_id'], unique=False)

    op.create_table('entity_alias',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False, comment='alias/nickname/title'),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_alias_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_alias_entity_id'), ['entity_id'], unique=False)

    op.create_table('faction_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_from_id', sa.Integer(), nullable=False),
    sa.Column('faction_to_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('established_at', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['faction_from_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_to_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faction_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faction_relationships_project_id'), ['project_id'], unique=False)

    op.create_table('foreshadowing_reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('suggested_chapter_range', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadowing_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadowing_reminders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreshadowing_reminders_status'), ['status'], unique=False)

    op.create_table('foreshadowing_resolutions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_number', sa.Integer(), nullable=False),
    sa.Column('resolution_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('resolution_type', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('reader_satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_at_chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadowing_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_levels',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False, comment='排序，表示等级高低，数字越大等级越高'),
    sa.Column('name', sa.String(length=128), nullable=False, comment="阶段名称，如 '筑基期'、'大魔导师'"),
    sa.Column('abilities', sa.Text(), nullable=True, comment='此阶段角色具有的能力表现'),
    sa.Column('limitations', sa.Text(), nullable=True, comment='此阶段角色的弱点或能力限制'),
    sa.Column('breakthrough_conditions', sa.Text(), nullable=True, comment='突破到下一等级的要求'),
    sa.ForeignKeyConstraint(['system_id'], ['power_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('power_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_levels_system_id'), ['system_id'], unique=False)

    op.create_table('blueprint_characters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identity', sa.String(length=255), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('relationship_to_protagonist', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('power_system_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='角色绑定的体系'),
    sa.Column('current_power_level_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='角色当前所处境界/等级'),
    sa.ForeignKeyConstraint(['current_power_level_id'], ['power_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['power_system_id'], ['power_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blueprint_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blueprint_characters_project_id'), ['project_id'], unique=False)

    op.create_table('faction_relationship_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('old_type', sa.String(length=64), nullable=True),
    sa.Column('new_type', sa.String(length=64), nullable=False),
    sa.Column('old_strength', sa.Integer(), nullable=True),
    sa.Column('new_strength', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['faction_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_detail', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('emotion_intensity', sa.Integer(), nullable=True),
    sa.Column('emotion_reason', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('inventory_changes', sa.JSON(), nullable=True),
    sa.Column('relationship_changes', sa.JSON(), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('power_changes', sa.JSON(), nullable=True),
    sa.Column('known_secrets', sa.JSON(), nullable=True),
    sa.Column('new_knowledge', sa.JSON(), nullable=True),
    sa.Column('current_goals', sa.JSON(), nullable=True),
    sa.Column('goal_progress', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_states_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_states_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_states_project_id'), ['project_id'], unique=False)

    op.create_table('faction_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faction_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faction_members_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faction_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faction_members_project_id'))

    op.drop_table('faction_members')
    with op.batch_alter_table('character_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_states_project_id'))
        batch_op.drop_index(batch_op.f('ix_character_states_character_id'))
        batch_op.drop_index(batch_op.f('ix_character_states_chapter_number'))

    op.drop_table('character_states')
    op.drop_table('faction_relationship_history')
    with op.batch_alter_table('blueprint_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blueprint_characters_project_id'))

    op.drop_table('blueprint_characters')
    with op.batch_alter_table('power_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_levels_system_id'))

    op.drop_table('power_levels')
    op.drop_table('foreshadowing_status_history')
    op.drop_table('foreshadowing_resolutions')
    with op.batch_alter_table('foreshadowing_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadowing_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_foreshadowing_reminders_project_id'))

    op.drop_table('foreshadowing_reminders')
    with op.batch_alter_table('faction_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faction_relationships_project_id'))

    op.drop_table('faction_relationships')
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_alias_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_alias_alias'))

    op.drop_table('entity_alias')
    with op.batch_alter_table('causal_chains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_causal_chains_project_id'))

    op.drop_table('causal_chains')
    with op.batch_alter_table('writer_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writer_personas_project_id'))

    op.drop_table('writer_personas')
    with op.batch_alter_table('volume_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_summaries_project_id'))

    op.drop_table('volume_summaries')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_chapter_number'))

    op.drop_table('timeline_events')
    op.drop_table('story_time_trackers')
    with op.batch_alter_table('project_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memories_project_id'))

    op.drop_table('project_memories')
    with op.batch_alter_table('power_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_systems_project_id'))

    op.drop_table('power_systems')
    with op.batch_alter_table('novel_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novel_conversations_project_id'))

    op.drop_table('novel_conversations')
    op.drop_table('novel_constitutions')
    op.drop_table('novel_blueprints')
    with op.batch_alter_table('foreshadowings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadowings_status'))
        batch_op.drop_index(batch_op.f('ix_foreshadowings_project_id'))

    op.drop_table('foreshadowings')
    op.drop_table('foreshadowing_analysis')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_project_id'))

    op.drop_table('factions')
    with op.batch_alter_table('entity_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_registry_project_id'))
        batch_op.drop_index(batch_op.f('ix_entity_registry_entity_type'))

    op.drop_table('entity_registry')
    with op.batch_alter_table('chapter_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_snapshots_chapter_number'))

    op.drop_table('chapter_snapshots')
    with op.batch_alter_table('chapter_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_outlines_project_id'))
        batch_op.drop_index('ix_chapter_outlines_project_chapter')

    op.drop_table('chapter_outlines')
    with op.batch_alter_table('chapter_blueprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_blueprints_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_blueprints_chapter_number'))

    op.drop_table('chapter_blueprints')
    with op.batch_alter_table('blueprint_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blueprint_relationships_project_id'))

    op.drop_table('blueprint_relationships')
    op.drop_table('user_writing_preferences')
    with op.batch_alter_table('user_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_quotas_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_quotas_id'))

    op.drop_table('user_quotas')
    with op.batch_alter_table('user_daily_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_requests_user_id'))

    op.drop_table('user_daily_requests')
    with op.batch_alter_table('reference_novels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_novels_user_id'))
        batch_op.drop_index(batch_op.f('ix_reference_novels_title'))

    op.drop_table('reference_novels')
    with op.batch_alter_table('novel_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novel_projects_user_id'))

    op.drop_table('novel_projects')
    op.drop_table('llm_configs')
    with op.batch_alter_table('chapter_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_reviews_project_id'))

    op.drop_table('chapter_reviews')
    with op.batch_alter_table('chapter_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_evaluations_chapter_id'))

    op.drop_table('chapter_evaluations')
    op.drop_table('blueprint_templates')
    with op.batch_alter_table('writing_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_templates_name'))
        batch_op.drop_index(batch_op.f('ix_writing_templates_category'))

    op.drop_table('writing_templates')
    with op.batch_alter_table('writing_archives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_archives_project_id'))
        batch_op.drop_index(batch_op.f('ix_writing_archives_imperial_edict_id'))

    op.drop_table('writing_archives')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    op.drop_table('usage_metrics')
    op.drop_table('update_logs')
    op.drop_table('system_configs')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_name'))

    op.drop_table('prompts')
    op.drop_table('plans')
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_status'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_plan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_channel'))

    op.drop_table('payment_orders')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_project_id'))
        batch_op.drop_index('ix_chapters_project_chapter')

    op.drop_table('chapters')
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_versions_chapter_id'))

    op.drop_table('chapter_versions')
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_log_date'))

    op.drop_table('api_usage_logs')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
